### login
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email" : "khalilbaidouri11@gmail.com",
  "password" : "khalilbaidouri11"
}

###
###My-predictions
GET localhost:8081/api/v1/matches/my-predictions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraGFsaWxiYWlkb3VyaTExQGdtYWlsLmNvbSIsImlhdCI6MTc2NzcyOTIzMiwiZXhwIjoxNzY3NzMwMTMyfQ.iOwenZ1QPRWVv44YcUiQj2-0Ns0U6FRNft8SD-UP-Io
